// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/command.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// ExecCmd mocks base method.
func (m *MockExecutor) ExecCmd(ctx context.Context, script string, ch <-chan int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecCmd", ctx, script, ch)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecCmd indicates an expected call of ExecCmd.
func (mr *MockExecutorMockRecorder) ExecCmd(ctx, script, ch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecCmd", reflect.TypeOf((*MockExecutor)(nil).ExecCmd), ctx, script, ch)
}
